name: $(BuildID).$(Date:yyyyMMdd).$(SourceBranchName)

trigger:
  branches:
    include:
      # in order as per GitFlow Branching strategy
      - 'main'
      - 'hotfix/FI0-*'
      - 'release/*'
      - 'develop'
      - 'feature/FI0-*'

parameters:
  - name: deployFromFeatureBranch
    displayName: 'Deploy from Feature Branch'
    type: boolean
    default: false

resources:
  repositories:
    - repository: MMOPipelineCommon
      name: mmo-fes-pipeline-common
      type: git
      ref: main

stages:
  - template: /includes/npm-package-build-publish.yaml@MMOPipelineCommon
    parameters:
      deployFromFeatureBranch: ${{ parameters.deployFromFeatureBranch }}
