sonar.projectKey=DEFRA_eutd-mmo-fes-reference-shared-data
sonar.projectName=eutd-mmo-fes-reference-shared-data
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/test/**
sonar.dynamicAnalysis=reuseReports
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.junit.reportPaths=./test-results/junit.xml
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
