sonar.projectKey=DEFRA-MMO-FES_mmo-fes-reference-shared-data_229d66bb-97f1-405d-9930-27298b390dc0
sonar.projectName=mmo-fes-reference-shared-data
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/test/**
sonar.dynamicAnalysis=reuseReports
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.junit.reportPaths=./test-results/junit.xml
