sonar.projectKey=DEFRA-EUX-MMO_mmo-shared-reference-data_AYw1mZLNzN5KmeT6-9Rk
sonar.projectName=mmo-shared-reference-data
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/test/**
sonar.dynamicAnalysis=reuseReports
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.junit.reportPaths=./test-results/junit.xml
